// 다국어 지원을 위한 언어 데이터
const translations = {
    ko: {
        title: "내손안에 슈퍼바이저 - 체험단 모집",
        "brand.name": "내손안에 슈퍼바이저",
        "search.placeholder": "체험단 상품을 찾아보세요!",
        "nav.main": "메인",
        "nav.experience": "체험단 모집",
        "nav.hotplace": "핫플 맛집",
        "nav.guide": "이용가이드",
        "nav.search": "체험단 검색",
        "nav.category": "카테고리",
        "nav.recruitment": "모집 공고",
        "nav.review": "이달의 리뷰",
        "nav.mypage": "마이페이지",
        "banner.title": "체험단 모집",
        "banner.subtitle": "진짜 검증된 체험단을 모집하세요요!",
        "banner.mission.title": "리뷰 작성 미션",
        "banner.mission.subtitle": "식사하고 포인트 받아가세요",
        "sections.popular": "추천 체험단",
        "sections.trending": "인기 체험단",
        "sections.new": "신규 체험단 모집",
        "sections.ending": "마감 임박 체험단",
        "footer.company": "회사소개",
        "footer.terms": "이용약관",
        "footer.privacy": "개인정보처리방침",
        "footer.support": "고객센터",
        "footer.partnership": "제휴문의",
        "footer.notice": "공지사항",
        "footer.careers": "채용정보",
        "footer.customer_service": "고객센터 10:00 ~ 18:00",
        "footer.address": "회사주소: 서울 강남구 영동대로 602",
        "footer.email": "이메일: nbbranding@naver.com",
        "footer.business_number": "사업자등록번호: 298-06-03540",
        "experience.title": "체험단 등록",
        "experience.load_previous": "이전 체험단 불러오기",
        "experience.basic_info": "기본 정보",
        "experience.company_name": "상호명",
        "experience.company_instruction": "방문형/포장형의 경우 네이버 플레이스에 등록되어 있는 업체명으로 입력해 주세요",
        "experience.company_placeholder": "상호명을 작성해 주세요",
        "experience.category": "카테고리",
        "experience.category_select": "선택",
        "experience.category_restaurant": "맛집",
        "experience.category_food": "식품",
        "experience.category_beauty": "뷰티",
        "experience.category_travel": "여행",
        "experience.category_digital": "디지털",
        "experience.category_pets": "반려동물",
        "experience.category_other": "기타",
        "experience.channels": "채널",
        "experience.channel_blog": "블로그",
        "experience.channel_blog_desc": "블로그 게시물 1건 업로드",
        "experience.channel_blog_clip": "블로그+클립",
        "experience.channel_blog_clip_desc": "1회 체험으로 블로그 게시물 1건+15초 영상(클립) 1개",
        "experience.channel_reels": "릴스",
        "experience.channel_reels_desc": "30초 이상의 영상(릴스) 1개 업로드",
        "experience.channel_shorts": "쇼츠",
        "experience.channel_shorts_desc": "30초 이상의 영상(유튜브 쇼츠) 1개 업로드",
        "experience.channel_instagram": "인스타그램",
        "experience.channel_instagram_desc": "사진 3장 이상의 피드 게시물 1개 업로드",
        "experience.channel_clip": "클립",
        "experience.channel_clip_desc": "30초 영상(클립) 1개 업로드",
        "experience.channel_youtube": "유튜브",
        "experience.channel_youtube_desc": "3분 이상의 영상(유튜브) 1개 업로드",
        "experience.channel_tiktok": "틱톡",
        "experience.channel_tiktok_desc": "30초 이상의 영상(틱톡) 1개 업로드",
        "experience.channel_xiaohongshu": "샤오홍슈",
        "experience.channel_xiaohongshu_desc": "샤오홍슈 게시물 1개 업로드",
        "experience.channel_twitter": "X(트위터)",
        "experience.channel_twitter_desc": "X(트위터) 게시물 1개 업로드",
        "experience.schedule": "체험 가능 요일 및 시간",
        "experience.available_days": "체험 가능 요일",
        "experience.day_monday": "월",
        "experience.day_tuesday": "화",
        "experience.day_wednesday": "수",
        "experience.day_thursday": "목",
        "experience.day_friday": "금",
        "experience.day_saturday": "토",
        "experience.day_sunday": "일",
        "experience.available_time": "체험 가능 시간",
        "experience.time_select": "선택",
        "experience.time_from": "부터",
        "experience.time_to": "까지",
        "experience.twenty_four_hours": "24시간 영업",
        "experience.same_day_booking": "당일 예약 및 방문",
        "experience.possible": "가능",
        "experience.impossible": "불가능",
        "experience.reservation_notes": "예약 시 주의사항 (선택)",
        "experience.reservation_notes_placeholder": "브레이크 타임 또는 예약 시 주의사항을 입력해 주세요",
        "experience.experience_settings": "체험단 설정",
        "experience.mission_guidelines": "체험단 미션",
        "experience.mission_info_1": "영수증 리뷰/네이버 예약은 불가합니다.",
        "experience.mission_info_2": "필수 가이드(사진 개수, 글자수 등)는 리뷰노트 가이드로 진행됩니다.",
        "experience.mission_prompt": "홍보를 하고 싶은 키워드 위주로 명확하게 작성해 주세요!",
        "experience.mission_examples": "예시:",
        "experience.mission_example_1": "- 3대 째 내려온 치킨집",
        "experience.mission_example_2": "- 바삭한 식감 강조",
        "experience.mission_example_3": "- 단체석, 회식, 넓은 주차장",
        "experience.mission_example_4": "- 감성적인 인테리어",
        "experience.mission_placeholder": "체험단 미션을 상세히 작성해주세요",
        "experience.promotion_keywords": "홍보할 검색 키워드",
        "experience.keyword_instruction": "키워드는 명확하게 3가지를 선택해서 작성해 주세요.",
        "experience.keyword_1": "키워드 1*",
        "experience.keyword_1_placeholder": "예) 강남역 맛집(10자 이내)",
        "experience.keyword_2": "키워드 2",
        "experience.keyword_2_placeholder": "예) 강남역 맛집(10자 이내)",
        "experience.keyword_3": "키워드 3",
        "experience.keyword_3_placeholder": "예) 강남역 맛집(10자 이내)",
        "experience.keyword_note_1": "*띄어쓰기까지 반영되므로 명확하게 작성해 주세요",
        "experience.keyword_note_2": "*해당 키워드는 리뷰 순위를 체크하는데 활용됩니다",
        "experience.naver_map_url": "네이버 지도 URL",
        "experience.naver_map_placeholder": "https://naver.me/...",
        "experience.naver_map_instruction": "네이버 지도에서 '공유' 버튼을 클릭하여 링크를 복사해주세요",
        "experience.service_details": "제공 내역 및 모집 인원",
        "experience.service_details_title": "제공 내역",
        "experience.service_details_instruction": "인플루언서에게 제공할 서비스를 입력해주세요",
        "experience.service_details_placeholder": "제공할 서비스나 상품에 대해 상세히 입력해주세요",
        "experience.service_warning": "가격과 품목을 명확히 표기하지 않으면 반려되니 주의하세요",
        "experience.recruitment_count": "체험단 모집 인원",
        "experience.people_unit": "명",
        "experience.thumbnail": "썸네일 등록",
        "experience.upload_instruction": "클릭 하거나 드래그/드롭 해주세요",
        "experience.upload_format": "5MB 이하의 JPEG, PNG 파일",
        "experience.upload_warning": "검수 불가 사진: 간판/로고/화면 캡쳐 / 텍스트가 크게 들어간 이미지",
        "experience.contact": "담당자 연락처",
        "experience.contact_phone": "담당자 연락처",
        "experience.details": "체험단 상세 정보",
        "experience.experience_title": "체험단 제목",
        "experience.experience_title_placeholder": "체험단 제목을 입력해주세요",
        "experience.description": "체험단 설명",
        "experience.description_placeholder": "체험단에 대한 자세한 설명을 입력해주세요",
        "experience.type": "체험 유형",
        "experience.type_select": "체험 유형을 선택해주세요",
        "experience.type_visit": "방문형",
        "experience.type_delivery": "배송형",
        "experience.type_pickup": "포장형",
        "experience.type_online": "온라인",
        "experience.type_hybrid": "하이브리드",
        "experience.participant_count": "모집 인원",
        "experience.start_date": "모집 시작일",
        "experience.end_date": "모집 마감일",
        "experience.additional_info": "추가 정보",
        "experience.location": "위치 (방문형인 경우)",
        "experience.location_placeholder": "주소를 입력해주세요",
        "experience.requirements": "참여 조건",
        "experience.requirements_placeholder": "참여 조건을 입력해주세요 (예: 연령, 성별, 지역 등)",
        "experience.benefits": "혜택",
        "experience.benefits_placeholder": "참여자에게 제공되는 혜택을 입력해주세요",
        "experience.cancel": "취소",
        "experience.next": "다음으로"
    },
    zh: {
        title: "我手中的监督员 - 体验团招募",
        "brand.name": "我手中的监督员",
        "search.placeholder": "搜索体验团商品！",
        "nav.main": "主页",
        "nav.experience": "体验团招募",
        "nav.hotplace": "热门餐厅",
        "nav.guide": "使用指南",
        "nav.search": "体验团搜索",
        "nav.category": "分类",
        "nav.recruitment": "招聘公告",
        "nav.review": "本月评论",
        "nav.mypage": "我的页面",
        "banner.title": "体验团招募",
        "banner.subtitle": "招募真正经过验证的体验团！",
        "banner.mission.title": "评论写作任务",
        "banner.mission.subtitle": "用餐并获得积分",
        "sections.popular": "推荐体验团",
        "sections.trending": "热门体验团",
        "sections.new": "新体验团招募",
        "sections.ending": "即将结束的体验团",
        "footer.company": "公司介绍",
        "footer.terms": "使用条款",
        "footer.privacy": "隐私政策",
        "footer.support": "客户支持",
        "footer.partnership": "合作咨询",
        "footer.notice": "公告",
        "footer.careers": "招聘信息",
        "footer.customer_service": "客户服务中心 10:00 ~ 18:00",
        "footer.address": "公司地址: 首尔江南区永东大道602",
        "footer.email": "邮箱: nbbranding@naver.com",
        "footer.business_number": "营业执照号: 298-06-03540",
        "experience.title": "体验团注册",
        "experience.load_previous": "加载之前的体验团",
        "experience.basic_info": "基本信息",
        "experience.company_name": "公司名称",
        "experience.company_instruction": "访问型/打包型请输入在Naver Place注册的公司名称",
        "experience.company_placeholder": "请输入公司名称",
        "experience.category": "类别",
        "experience.category_select": "选择",
        "experience.category_restaurant": "餐厅",
        "experience.category_food": "食品",
        "experience.category_beauty": "美容",
        "experience.category_travel": "旅游",
        "experience.category_digital": "数码",
        "experience.category_pets": "宠物",
        "experience.category_other": "其他",
        "experience.channels": "频道",
        "experience.channel_blog": "博客",
        "experience.channel_blog_desc": "上传1篇博客文章",
        "experience.channel_blog_clip": "博客+短视频",
        "experience.channel_blog_clip_desc": "1次体验上传1篇博客文章+1个15秒视频(短视频)",
        "experience.channel_reels": "Reels",
        "experience.channel_reels_desc": "上传1个30秒以上的视频(Reels)",
        "experience.channel_shorts": "Shorts",
        "experience.channel_shorts_desc": "上传1个30秒以上的视频(YouTube Shorts)",
        "experience.channel_instagram": "Instagram",
        "experience.channel_instagram_desc": "上传1个包含3张以上照片的Feed帖子",
        "experience.channel_clip": "短视频",
        "experience.channel_clip_desc": "上传1个30秒视频(短视频)",
        "experience.channel_youtube": "YouTube",
        "experience.channel_youtube_desc": "上传1个3分钟以上的视频(YouTube)",
        "experience.channel_tiktok": "TikTok",
        "experience.channel_tiktok_desc": "上传1个30秒以上的视频(TikTok)",
        "experience.channel_xiaohongshu": "小红书",
        "experience.channel_xiaohongshu_desc": "上传1个小红书帖子",
        "experience.channel_twitter": "X(推特)",
        "experience.channel_twitter_desc": "上传1个X(推特)帖子",
        "experience.service_details": "服务详情及招募人数",
        "experience.service_details_title": "服务详情",
        "experience.service_details_instruction": "请输入要提供给影响者的服务",
        "experience.service_details_placeholder": "请详细输入要提供的服务或商品",
        "experience.service_warning": "请注意，如果不明确标注价格和物品，可能会被拒绝",
        "experience.recruitment_count": "体验团招募人数",
        "experience.people_unit": "人",
        "experience.thumbnail": "缩略图注册",
        "experience.upload_instruction": "点击或拖拽/放置",
        "experience.upload_format": "5MB以下的JPEG、PNG文件",
        "experience.upload_warning": "审核不可的照片：招牌/标志/屏幕截图/包含大文字的图像",
        "experience.contact": "负责人联系方式",
        "experience.contact_phone": "负责人联系方式",
        "experience.details": "体验团详细信息",
        "experience.experience_title": "体验团标题",
        "experience.experience_title_placeholder": "请输入体验团标题",
        "experience.description": "体验团说明",
        "experience.description_placeholder": "请输入体验团的详细说明",
        "experience.type": "体验类型",
        "experience.type_select": "请选择体验类型",
        "experience.type_visit": "访问型",
        "experience.type_delivery": "配送型",
        "experience.type_pickup": "打包型",
        "experience.type_online": "在线",
        "experience.type_hybrid": "混合型",
        "experience.participant_count": "招募人数",
        "experience.start_date": "招募开始日期",
        "experience.end_date": "招募截止日期",
        "experience.additional_info": "附加信息",
        "experience.location": "位置（访问型情况）",
        "experience.location_placeholder": "请输入地址",
        "experience.requirements": "参与条件",
        "experience.requirements_placeholder": "请输入参与条件（例如：年龄、性别、地区等）",
        "experience.benefits": "福利",
        "experience.benefits_placeholder": "请输入提供给参与者的福利",
        "experience.cancel": "取消",
        "experience.next": "下一步"
    },
    en: {
        title: "Supervisor in My Hand - Experience Group Recruitment",
        "brand.name": "Supervisor in My Hand",
        "search.placeholder": "Search for experience group products!",
        "nav.main": "Main",
        "nav.experience": "Experience Groups",
        "nav.hotplace": "Hot Places",
        "nav.guide": "Guide",
        "nav.search": "Search",
        "nav.category": "Category",
        "nav.recruitment": "Recruitment",
        "nav.review": "Reviews",
        "nav.mypage": "My Page",
        "banner.title": "Experience Group Recruitment",
        "banner.subtitle": "Recruit truly verified experience groups!",
        "banner.mission.title": "Review Writing Mission",
        "banner.mission.subtitle": "Eat and earn points",
        "sections.popular": "Recommended Experience Groups",
        "sections.trending": "Trending Experience Groups",
        "sections.new": "New Experience Group Recruitment",
        "sections.ending": "Ending Soon Experience Groups",
        "footer.company": "About Us",
        "footer.terms": "Terms of Use",
        "footer.privacy": "Privacy Policy",
        "footer.support": "Customer Support",
        "footer.partnership": "Partnership",
        "footer.notice": "Notice",
        "footer.careers": "Careers",
        "footer.customer_service": "Customer Service 10:00 ~ 18:00",
        "footer.address": "Address: 602 Yeongdong-daero, Gangnam-gu, Seoul",
        "footer.email": "Email: nbbranding@naver.com",
        "footer.business_number": "Business Registration Number: 298-06-03540",
        "experience.title": "Experience Group Registration",
        "experience.load_previous": "Load Previous Experience Group",
        "experience.basic_info": "Basic Information",
        "experience.company_name": "Company Name",
        "experience.company_instruction": "For visit/pickup types, please enter the company name registered on Naver Place",
        "experience.company_placeholder": "Please enter the company name",
        "experience.category": "Category",
        "experience.category_select": "Select",
        "experience.category_restaurant": "Restaurants",
        "experience.category_food": "Food Products",
        "experience.category_beauty": "Beauty",
        "experience.category_travel": "Travel",
        "experience.category_digital": "Digital",
        "experience.category_pets": "Pets",
        "experience.category_other": "Other",
        "experience.channels": "Channels",
        "experience.channel_blog": "Blog",
        "experience.channel_blog_desc": "Upload 1 blog post",
        "experience.channel_blog_clip": "Blog+Clip",
        "experience.channel_blog_clip_desc": "1 blog post + 1 15-second video (clip) for 1 experience",
        "experience.channel_reels": "Reels",
        "experience.channel_reels_desc": "Upload 1 video (Reels) longer than 30 seconds",
        "experience.channel_shorts": "Shorts",
        "experience.channel_shorts_desc": "Upload 1 video (YouTube Shorts) longer than 30 seconds",
        "experience.channel_instagram": "Instagram",
        "experience.channel_instagram_desc": "Upload 1 feed post with 3 or more photos",
        "experience.channel_clip": "Clip",
        "experience.channel_clip_desc": "Upload 1 30-second video (clip)",
        "experience.channel_youtube": "YouTube",
        "experience.channel_youtube_desc": "Upload 1 video (YouTube) longer than 3 minutes",
        "experience.channel_tiktok": "TikTok",
        "experience.channel_tiktok_desc": "Upload 1 video (TikTok) longer than 30 seconds",
        "experience.channel_xiaohongshu": "Xiaohongshu",
        "experience.channel_xiaohongshu_desc": "Upload 1 Xiaohongshu post",
        "experience.channel_twitter": "X(Twitter)",
        "experience.channel_twitter_desc": "Upload 1 X(Twitter) post",
        "experience.service_details": "Service Details and Recruitment",
        "experience.service_details_title": "Service Details",
        "experience.service_details_instruction": "Please enter the service to be provided to influencers",
        "experience.service_details_placeholder": "Please enter details about the service or product to be provided",
        "experience.service_warning": "Please note that if price and items are not clearly indicated, it may be rejected",
        "experience.recruitment_count": "Experience Group Recruitment Count",
        "experience.people_unit": "people",
        "experience.thumbnail": "Thumbnail Registration",
        "experience.upload_instruction": "Click or drag/drop",
        "experience.upload_format": "JPEG, PNG files under 5MB",
        "experience.upload_warning": "Unacceptable photos for review: Signboards / Logos / Screenshots / Images with large text",
        "experience.contact": "Contact Person's Contact Information",
        "experience.contact_phone": "Contact Person's Contact Information",
        "experience.details": "Experience Group Details",
        "experience.experience_title": "Experience Group Title",
        "experience.experience_title_placeholder": "Please enter the experience group title",
        "experience.description": "Experience Group Description",
        "experience.description_placeholder": "Please enter detailed description of the experience group",
        "experience.type": "Experience Type",
        "experience.type_select": "Please select experience type",
        "experience.type_visit": "Visit Type",
        "experience.type_delivery": "Delivery Type",
        "experience.type_pickup": "Pickup Type",
        "experience.type_online": "Online",
        "experience.type_hybrid": "Hybrid",
        "experience.participant_count": "Number of Participants",
        "experience.start_date": "Recruitment Start Date",
        "experience.end_date": "Recruitment End Date",
        "experience.additional_info": "Additional Information",
        "experience.location": "Location (for visit type)",
        "experience.location_placeholder": "Please enter the address",
        "experience.requirements": "Participation Requirements",
        "experience.requirements_placeholder": "Please enter participation requirements (e.g., age, gender, region, etc.)",
        "experience.benefits": "Benefits",
        "experience.benefits_placeholder": "Please enter benefits provided to participants",
        "experience.cancel": "Cancel",
        "experience.next": "Next"
    },
    ja: {
        title: "私の手の中のスーパーバイザー - 体験団募集",
        "brand.name": "私の手の中のスーパーバイザー",
        "search.placeholder": "体験団商品を検索してください！",
        "nav.main": "メイン",
        "nav.experience": "体験団募集",
        "nav.hotplace": "人気レストラン",
        "nav.guide": "利用ガイド",
        "nav.search": "体験団検索",
        "nav.category": "カテゴリー",
        "nav.recruitment": "募集公告",
        "nav.review": "今月のレビュー",
        "nav.mypage": "マイページ",
        "banner.title": "体験団募集",
        "banner.subtitle": "本当に検証された体験団を募集しましょう！",
        "banner.mission.title": "レビュー作成ミッション",
        "banner.mission.subtitle": "食事してポイントをもらいましょう",
        "sections.popular": "おすすめ体験団",
        "sections.trending": "人気体験団",
        "sections.new": "新規体験団募集",
        "sections.ending": "終了間近体験団",
        "footer.company": "会社紹介",
        "footer.terms": "利用規約",
        "footer.privacy": "プライバシーポリシー",
        "footer.support": "カスタマーサポート",
        "footer.partnership": "パートナーシップ",
        "footer.notice": "お知らせ",
        "footer.careers": "求人情報",
        "footer.customer_service": "カスタマーサービス 10:00 ~ 18:00",
        "footer.address": "会社住所: ソウル江南区永東大路602",
        "footer.email": "メール: nbbranding@naver.com",
        "footer.business_number": "事業者登録番号: 298-06-03540",
        "experience.title": "体験団登録",
        "experience.load_previous": "以前の体験団を読み込む",
        "experience.basic_info": "基本情報",
        "experience.company_name": "会社名",
        "experience.company_instruction": "訪問型/テイクアウト型の場合は、Naver Placeに登録されている会社名で入力してください",
        "experience.company_placeholder": "会社名を入力してください",
        "experience.category": "カテゴリー",
        "experience.category_select": "選択",
        "experience.category_restaurant": "レストラン",
        "experience.category_food": "食品",
        "experience.category_beauty": "美容",
        "experience.category_travel": "旅行",
        "experience.category_digital": "デジタル",
        "experience.category_pets": "ペット",
        "experience.category_other": "その他",
        "experience.channels": "チャンネル",
        "experience.channel_blog": "ブログ",
        "experience.channel_blog_desc": "ブログ記事1件アップロード",
        "experience.channel_blog_clip": "ブログ+クリップ",
        "experience.channel_blog_clip_desc": "1回の体験でブログ記事1件+15秒動画(クリップ)1個",
        "experience.channel_reels": "リールス",
        "experience.channel_reels_desc": "30秒以上の動画(リールス)1個アップロード",
        "experience.channel_shorts": "ショーツ",
        "experience.channel_shorts_desc": "30秒以上の動画(YouTubeショーツ)1個アップロード",
        "experience.channel_instagram": "Instagram",
        "experience.channel_instagram_desc": "写真3枚以上のフィード投稿1個アップロード",
        "experience.channel_clip": "クリップ",
        "experience.channel_clip_desc": "30秒動画(クリップ)1個アップロード",
        "experience.channel_youtube": "YouTube",
        "experience.channel_youtube_desc": "3分以上の動画(YouTube)1個アップロード",
        "experience.channel_tiktok": "TikTok",
        "experience.channel_tiktok_desc": "30秒以上の動画(TikTok)1個アップロード",
        "experience.channel_xiaohongshu": "小紅書",
        "experience.channel_xiaohongshu_desc": "小紅書投稿1個アップロード",
        "experience.channel_twitter": "X(ツイッター)",
        "experience.channel_twitter_desc": "X(ツイッター)投稿1個アップロード",
        "experience.service_details": "提供内容及び募集人数",
        "experience.service_details_title": "提供内容",
        "experience.service_details_instruction": "インフルエンサーに提供するサービスを入力してください",
        "experience.service_details_placeholder": "提供するサービスや商品について詳しく入力してください",
        "experience.service_warning": "価格と品目を明確に表示しない場合は拒否される可能性があるので注意してください",
        "experience.recruitment_count": "体験団募集人数",
        "experience.people_unit": "名",
        "experience.thumbnail": "サムネイル登録",
        "experience.upload_instruction": "クリックまたはドラッグ/ドロップしてください",
        "experience.upload_format": "5MB以下のJPEG、PNGファイル",
        "experience.upload_warning": "審査不可写真: 看板/ロゴ/画面キャプチャ/大きなテキストが入った画像",
        "experience.contact": "担当者連絡先",
        "experience.contact_phone": "担当者連絡先",
        "experience.details": "体験団詳細情報",
        "experience.experience_title": "体験団タイトル",
        "experience.experience_title_placeholder": "体験団タイトルを入力してください",
        "experience.description": "体験団説明",
        "experience.description_placeholder": "体験団の詳細な説明を入力してください",
        "experience.type": "体験タイプ",
        "experience.type_select": "体験タイプを選択してください",
        "experience.type_visit": "訪問型",
        "experience.type_delivery": "配送型",
        "experience.type_pickup": "テイクアウト型",
        "experience.type_online": "オンライン",
        "experience.type_hybrid": "ハイブリッド",
        "experience.participant_count": "募集人数",
        "experience.start_date": "募集開始日",
        "experience.end_date": "募集締切日",
        "experience.additional_info": "追加情報",
        "experience.location": "場所（訪問型の場合）",
        "experience.location_placeholder": "住所を入力してください",
        "experience.requirements": "参加条件",
        "experience.requirements_placeholder": "参加条件を入力してください（例：年齢、性別、地域など）",
        "experience.benefits": "特典",
        "experience.benefits_placeholder": "参加者に提供される特典を入力してください",
        "experience.cancel": "キャンセル",
        "experience.next": "次へ"
    }
};

// 현재 언어 설정 (기본값: 한국어)
let currentLanguage = localStorage.getItem('language') || 'ko';

// DOM 요소들
const languageBtn = document.getElementById('languageBtn');
const languageDropdown = document.getElementById('languageDropdown');
const currentLanguageSpan = document.getElementById('currentLanguage');

// 언어 변경 함수
function changeLanguage(lang) {
    currentLanguage = lang;
    localStorage.setItem('language', lang);
    
    // HTML lang 속성 업데이트
    document.documentElement.lang = lang;
    
    // 현재 선택된 언어 표시 업데이트
    const languageNames = {
        'ko': '한국어',
        'zh': '中文',
        'en': 'English',
        'ja': '日本語'
    };
    currentLanguageSpan.textContent = languageNames[lang];
    
    // 모든 번역 가능한 요소들 업데이트
    const elementsToTranslate = document.querySelectorAll('[data-translate]');
    elementsToTranslate.forEach(element => {
        const key = element.getAttribute('data-translate');
        if (translations[lang] && translations[lang][key]) {
            if (element.tagName === 'INPUT' && element.type === 'text') {
                element.placeholder = translations[lang][key];
            } else {
                element.textContent = translations[lang][key];
            }
        }
    });
    
    // 드롭다운 닫기
    languageDropdown.classList.remove('show');
}

// 언어 선택 이벤트 리스너
document.addEventListener('DOMContentLoaded', function() {
    // 초기 언어 설정
    changeLanguage(currentLanguage);
    
    // 언어 버튼 클릭 이벤트
    languageBtn.addEventListener('click', function(e) {
        e.stopPropagation();
        languageDropdown.classList.toggle('show');
    });
    
    // 언어 옵션 클릭 이벤트
    const languageOptions = document.querySelectorAll('.language-option');
    languageOptions.forEach(option => {
        option.addEventListener('click', function() {
            const selectedLang = this.getAttribute('data-lang');
            changeLanguage(selectedLang);
        });
    });
    
    // 외부 클릭 시 드롭다운 닫기
    document.addEventListener('click', function(e) {
        if (!languageBtn.contains(e.target) && !languageDropdown.contains(e.target)) {
            languageDropdown.classList.remove('show');
        }
    });
    
    // 드롭다운 내부 클릭 시 이벤트 전파 방지
    languageDropdown.addEventListener('click', function(e) {
        e.stopPropagation();
    });
});
